server:
  port: 8080
  context-path: /base

spring:
  datasource:
    name: test1
    url: jdbc:mysql://localhost:3306/movie_calendar?characterEncoding=utf-8&useUnicode=true&useSSL=false
    #url: jdbc:mysql://118.89.246.143:3306/movie_calendar?characterEncoding=utf-8&useUnicode=true&useSSL=false
    username: root
    password: $Aa3141592620170101#movie_calendar
    # 使用druid数据源
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    initialize: true #指定初始化数据源，是否用data.sql来初始化，默认: true
  session:
    store-type: hash_map
  thymeleaf:
    cache: false
  http:
    encoding:
      charset: UTF-8
      force: true
#  groovy:
#    template:
#      resource-loader-path: classpath:/templates/admin/*
  #静态资源配置写在WebMvcConfig.java里
  #resources:
  #  static-locations: classpath:/static/picture/
  #mvc:
  #  static-path-pattern: /picture/**

mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: net.meing.wxsmall.model

#mapper:
#    mappers:
#        - tk.mybatis.springboot.util.MyMapper
#    not-empty: false
#    identity: MYSQL

logging:
  #pattern:
    #level: 日志：%5p
    #console: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{50} ------ %msg%n"
  level:
    org.springframework: INFO
    tk.mybatis: INFO

custom:
  system:
    appid: wx740101893335fe4d
    secret: d0affcd1cf7499b5caf1bec15a849ff1
  login:
    expire: 86400
    develop:
      enable: true
      password: glgjssyqyhfbqz
  image:
    path: /www/picture
    thumbnail:
      high: 500
